/**
 * CAPSULE ACTION TYPES
 */

export const GET_CAPSULE_LIST = 'GET_CAPSULE_LIST';
export const GET_CAPSULE_LIST_SUCCESS = 'GET_CAPSULE_LIST_SUCCESS';
export const GET_CAPSULE_LIST_ERROR = 'GET_CAPSULE_LIST_ERROR';

export const GET_CAPSULE_DETAILS = 'GET_CAPSULE_DETAILS';
export const GET_CAPSULE_DETAILS_SUCCESS = 'GET_CAPSULE_DETAILS_SUCCESS';
export const GET_CAPSULE_DETAILS_ERROR = 'GET_CAPSULE_DETAILS_ERROR';

export const GET_UPCOMING_CAPSULE_LIST = 'GET_UPCOMING_CAPSULE_LIST';
export const GET_UPCOMING_CAPSULE_LIST_SUCCESS = 'GET_UPCOMING_CAPSULE_LIST_SUCCESS';
export const GET_UPCOMING_CAPSULE_LIST_ERROR = 'GET_UPCOMING_CAPSULE_LIST_ERROR';

export const GET_PAST_CAPSULE_LIST = 'GET_PAST_CAPSULE_LIST';
export const GET_PAST_CAPSULE_LIST_SUCCESS = 'GET_PAST_CAPSULE_LIST_SUCCESS';
export const GET_PAST_CAPSULE_LIST_ERROR = 'GET_PAST_CAPSULE_LIST_ERROR';

//END

/**
 * CORE ACTION TYPES
 */

export const GET_CORE_LIST = 'GET_CORE_LIST';
export const GET_CORE_LIST_SUCCESS = 'GET_CORE_LIST_SUCCESS';
export const GET_CORE_LIST_ERROR = 'GET_CORE_LIST_ERROR';

export const GET_CORE_DETAILS = 'GET_CORE_DETAILS';
export const GET_CORE_DETAILS_SUCCESS = 'GET_CORE_DETAILS_SUCCESS';
export const GET_CORE_DETAILS_ERROR = 'GET_CORE_DETAILS_ERROR';

export const GET_UPCOMING_CORE_LIST = 'GET_UPCOMING_CORE_LIST';
export const GET_UPCOMING_CORE_LIST_SUCCESS = 'GET_UPCOMING_CORE_LIST_SUCCESS';
export const GET_UPCOMING_CORE_LIST_ERROR = 'GET_UPCOMING_CORE_LIST_ERROR';

export const GET_PAST_CORE_LIST = 'GET_PAST_CORE_LIST';
export const GET_PAST_CORE_LIST_SUCCESS = 'GET_PAST_CORE_LIST_SUCCESS';
export const GET_PAST_CORE_LIST_ERROR = 'GET_PAST_CORE_LIST_ERROR';

//END

/**
 * DRAGON ACTION TYPES
 */

export const GET_DRAGON_LIST = 'GET_DRAGON_LIST';
export const GET_DRAGON_LIST_SUCCESS = 'GET_DRAGON_LIST_SUCCESS';
export const GET_DRAGON_LIST_ERROR = 'GET_DRAGON_LIST_ERROR';

export const GET_DRAGON_DETAILS = 'GET_DRAGON_DETAILS';
export const GET_DRAGON_DETAILS_SUCCESS = 'GET_DRAGON_DETAILS_SUCCESS';
export const GET_DRAGON_DETAILS_ERROR = 'GET_DRAGON_DETAILS_ERROR';

//END

/**
 * HISTORY ACTION TYPES
 */

export const GET_HISTORY_LIST = 'GET_HISTORY_LIST';
export const GET_HISTORY_LIST_SUCCESS = 'GET_HISTORY_LIST_SUCCESS';
export const GET_HISTORY_LIST_ERROR = 'GET_HISTORY_LIST_ERROR';

export const GET_HISTORY_DETAILS = 'GET_HISTORY_DETAILS';
export const GET_HISTORY_DETAILS_SUCCESS = 'GET_HISTORY_DETAILS_SUCCESS';
export const GET_HISTORY_DETAILS_ERROR = 'GET_HISTORY_DETAILS_ERROR';

//END

/**
 * LANDING PADS ACTION TYPES
 */

export const GET_LANDING_PADS_LIST = 'GET_LANDING_PADS_LIST';
export const GET_LANDING_PADS_LIST_SUCCESS = 'GET_LANDING_PADS_LIST_SUCCESS';
export const GET_LANDING_PADS_LIST_ERROR = 'GET_LANDING_PADS_LIST_ERROR';

export const GET_LANDING_PADS_DETAILS = 'GET_LANDING_PADS_DETAILS';
export const GET_LANDING_PADS_DETAILS_SUCCESS = 'GET_LANDING_PADS_DETAILS_SUCCESS';
export const GET_LANDING_PADS_DETAILS_ERROR = 'GET_LANDING_PADS_DETAILS_ERROR';

//END


/**
 * LAUNCHES ACTION TYPES
 */

export const GET_LAUNCHES_LIST = 'GET_LAUNCHES_LIST';
export const GET_LAUNCHES_LIST_SUCCESS = 'GET_LAUNCHES_LIST_SUCCESS';
export const GET_LAUNCHES_LIST_ERROR = 'GET_LAUNCHES_LIST_ERROR';

export const GET_LAUNCHES_DETAILS = 'GET_LAUNCHES_DETAILS';
export const GET_LAUNCHES_DETAILS_SUCCESS = 'GET_LAUNCHES_DETAILS_SUCCESS';
export const GET_LAUNCHES_DETAILS_ERROR = 'GET_LAUNCHES_DETAILS_ERROR';

export const GET_UPCOMING_LAUNCHES_LIST = 'GET_UPCOMING_LAUNCHES_LIST';
export const GET_UPCOMING_LAUNCHES_LIST_SUCCESS = 'GET_UPCOMING_LAUNCHES_LIST_SUCCESS';
export const GET_UPCOMING_LAUNCHES_LIST_ERROR = 'GET_UPCOMING_LAUNCHES_LIST_ERROR';

export const GET_PAST_LAUNCHES_LIST = 'GET_PAST_LAUNCHES_LIST';
export const GET_PAST_LAUNCHES_LIST_SUCCESS = 'GET_PAST_LAUNCHES_LIST_SUCCESS';
export const GET_PAST_LAUNCHES_LIST_ERROR = 'GET_PAST_LAUNCHES_LIST_ERROR';

export const GET_LATEST_LAUNCHES_LIST = 'GET_LATEST_LAUNCHES_LIST';
export const GET_LATEST_LAUNCHES_LIST_SUCCESS = 'GET_LATEST_LAUNCHES_LIST_SUCCESS';
export const GET_LATEST_LAUNCHES_LIST_ERROR = 'GET_LATEST_LAUNCHES_LIST_ERROR';

export const GET_NEXT_LAUNCHES_LIST = 'GET_NEXT_LAUNCHES_LIST';
export const GET_NEXT_LAUNCHES_LIST_SUCCESS = 'GET_NEXT_LAUNCHES_LIST_SUCCESS';
export const GET_NEXT_LAUNCHES_LIST_ERROR = 'GET_NEXT_LAUNCHES_LIST_ERROR';

//END

/**
 * LAUNCH PADS ACTION TYPES
 */

export const GET_LAUNCH_PADS_LIST = 'GET_LAUNCH_PADS_LIST';
export const GET_LAUNCH_PADS_LIST_SUCCESS = 'GET_LAUNCH_PADS_LIST_SUCCESS';
export const GET_LAUNCH_PADS_LIST_ERROR = 'GET_LAUNCH_PADS_LIST_ERROR';

export const GET_LAUNCH_PADS_DETAILS = 'GET_LAUNCH_PADS_DETAILS';
export const GET_LAUNCH_PADS_DETAILS_SUCCESS = 'GET_LAUNCH_PADS_DETAILS_SUCCESS';
export const GET_LAUNCH_PADS_DETAILS_ERROR = 'GET_LAUNCH_PADS_DETAILS_ERROR';

//END

/**
 * MISSION ACTION TYPES
 */

export const GET_MISSION_LIST = 'GET_MISSION_LIST';
export const GET_MISSION_LIST_SUCCESS = 'GET_MISSION_LIST_SUCCESS';
export const GET_MISSION_LIST_ERROR = 'GET_MISSION_LIST_ERROR';

export const GET_MISSION_DETAILS = 'GET_MISSION_DETAILS';
export const GET_MISSION_DETAILS_SUCCESS = 'GET_MISSION_DETAILS_SUCCESS';
export const GET_MISSION_DETAILS_ERROR = 'GET_MISSION_DETAILS_ERROR';

//END

/**
 * PAYLOAD ACTION TYPES
 */

export const GET_PAYLOAD_LIST = 'GET_PAYLOAD_LIST';
export const GET_PAYLOAD_LIST_SUCCESS = 'GET_PAYLOAD_LIST_SUCCESS';
export const GET_PAYLOAD_LIST_ERROR = 'GET_PAYLOAD_LIST_ERROR';

export const GET_PAYLOAD_DETAILS = 'GET_PAYLOAD_DETAILS';
export const GET_PAYLOAD_DETAILS_SUCCESS = 'GET_PAYLOAD_DETAILS_SUCCESS';
export const GET_PAYLOAD_DETAILS_ERROR = 'GET_PAYLOAD_DETAILS_ERROR';

//END

/**
 * ROADSTER ACTION TYPES
 */

export const GET_ROADSTER_LIST = 'GET_ROADSTER_LIST';
export const GET_ROADSTER_LIST_SUCCESS = 'GET_ROADSTER_LIST_SUCCESS';
export const GET_ROADSTER_LIST_ERROR = 'GET_ROADSTER_LIST_ERROR';

export const GET_ROADSTER_DETAILS = 'GET_ROADSTER_DETAILS';
export const GET_ROADSTER_DETAILS_SUCCESS = 'GET_ROADSTER_DETAILS_SUCCESS';
export const GET_ROADSTER_DETAILS_ERROR = 'GET_ROADSTER_DETAILS_ERROR';

//END

/**
 * ROCKET ACTION TYPES
 */

export const GET_ROCKET_LIST = 'GET_ROCKET_LIST';
export const GET_ROCKET_LIST_SUCCESS = 'GET_ROCKET_LIST_SUCCESS';
export const GET_ROCKET_LIST_ERROR = 'GET_ROCKET_LIST_ERROR';

export const GET_ROCKET_DETAILS = 'GET_ROCKET_DETAILS';
export const GET_ROCKET_DETAILS_SUCCESS = 'GET_ROCKET_DETAILS_SUCCESS';
export const GET_ROCKET_DETAILS_ERROR = 'GET_ROCKET_DETAILS_ERROR';

//END

/**
 * SHIPS ACTION TYPES
 */

export const GET_SHIPS_LIST = 'GET_SHIPS_LIST';
export const GET_SHIPS_LIST_SUCCESS = 'GET_SHIPS_LIST_SUCCESS';
export const GET_SHIPS_LIST_ERROR = 'GET_SHIPS_LIST_ERROR';

export const GET_SHIPS_DETAILS = 'GET_SHIPS_DETAILS';
export const GET_SHIPS_DETAILS_SUCCESS = 'GET_SHIPS_DETAILS_SUCCESS';
export const GET_SHIPS_DETAILS_ERROR = 'GET_SHIPS_DETAILS_ERROR';

//END
