/**
 * SHIPS ACTION TYPES
 */

export const GET_SHIPS_LIST = 'GET_SHIPS_LIST';
export const GET_SHIPS_LIST_SUCCESS = 'GET_SHIPS_LIST_SUCCESS';
export const GET_SHIPS_LIST_ERROR = 'GET_SHIPS_LIST_ERROR';

export const GET_SHIPS_DETAILS = 'GET_SHIPS_DETAILS';
export const GET_SHIPS_DETAILS_SUCCESS = 'GET_SHIPS_DETAILS_SUCCESS';
export const GET_SHIPS_DETAILS_ERROR = 'GET_SHIPS_DETAILS_ERROR';

//END
